import { Cell, type Layout } from './treasureWorld'

// ステージは 24x32 の絵文字マップで持つ。1文字が 4x4 ます（CELL_SCALE）に広がり、
// 実際の ばんめんは 96x128 ます になる。手で読める形のまま置いておくことで、
// 地形の調整を数値の羅列ではなく見た目で行えるようにしている。
export const MAP_WIDTH = 24
export const MAP_HEIGHT = 32
export const CELL_SCALE = 4
export const WORLD_WIDTH = MAP_WIDTH * CELL_SCALE
export const WORLD_HEIGHT = MAP_HEIGHT * CELL_SCALE

// '.' そら / 's' すな / 'g' たから入りのすな / 'G' たからのかたまり / 'w' みず
// 'd' つち（ほれる） / 'r' いわ（ほれない） / 'o' あな / 'b' たからばこ / 'f' いずみ
const MATERIALS: Record<string, number> = {
  '.': Cell.Empty, s: Cell.Sand, w: Cell.Water, d: Cell.Dirt, r: Cell.Rock, o: Cell.Drain, b: Cell.Box, f: Cell.Spring,
}

export type Stage = {
  id: string
  name: string
  /** プレイ中に出す1行ヒント。 */
  hint: string
  /** クリアに必要な たからの つぶ数。 */
  need: number
  map: readonly string[]
}

/** 'g' は 4x4 の まんなか 2x2 だけを たからにする。すなの中に つぶが 散っている見た目になる。 */
function expand(symbol: string, dx: number, dy: number): number {
  if (symbol === 'G') return Cell.Gem
  if (symbol !== 'g') return MATERIALS[symbol]
  const inner = dx >= 1 && dx <= 2 && dy >= 1 && dy <= 2
  return inner ? Cell.Gem : Cell.Sand
}

export function buildLayout(stage: Stage, scale = CELL_SCALE): Layout & { gems: number } {
  const width = stage.map[0].length * scale
  const height = stage.map.length * scale
  const cells = new Uint8Array(width * height)
  let gems = 0
  for (let row = 0; row < stage.map.length; row++) for (let column = 0; column < stage.map[row].length; column++) {
    const symbol = stage.map[row][column]
    for (let dy = 0; dy < scale; dy++) for (let dx = 0; dx < scale; dx++) {
      const material = expand(symbol, dx, dy)
      cells[(row * scale + dy) * width + column * scale + dx] = material
      if (material === Cell.Gem) gems++
    }
  }
  return { width, height, cells, gems }
}

export const STAGES: readonly Stage[] = [
  {
    id: 'first-dig', name: 'はじめての あな', hint: 'つちを ほって、たからを おとそう', need: 24,
    map: [
      '........................',
      '........................',
      '........................',
      '.........ssss...........',
      '........ssggss..........',
      '.......ssggggss.........',
      '......ssssggssss........',
      '.....ssssssssssss.......',
      'rrrrrddddddddddddrrrrrrr',
      'rrrrrddddddddddddrrrrrrr',
      'rrrrr............rrrrrrr',
      'rrrrr............rrrrrrr',
      'rrrrrr..........rrrrrrrr',
      'rrrrrr..........rrrrrrrr',
      'rrrrrrr........rrrrrrrrr',
      'rrrrrrr........rrrrrrrrr',
      'rrrrrrrr......rrrrrrrrrr',
      'rrrrrrrr......rrrrrrrrrr',
      'rrrrrrrr......rrrrrrrrrr',
      'rrrrrrrr......rrrrrrrrrr',
      'rrrrrrrr......rrrrrrrrrr',
      'rrrrrrrr......rrrrrrrrrr',
      'rrrrrrrr......rrrrrrrrrr',
      'rrrrrrrr......rrrrrrrrrr',
      'rrrrrrrr......rrrrrrrrrr',
      'rrrrrrrr......rrrrrrrrrr',
      'rrrrrrrr......rrrrrrrrrr',
      'rrrrrrrr......rrrrrrrrrr',
      'rrrrrrrrbbbbbbrrrrrrrrrr',
      'rrrrrrrrbbbbbbrrrrrrrrrr',
      'rrrrrrrrbbbbbbrrrrrrrrrr',
      'rrrrrrrrrrrrrrrrrrrrrrrr',
    ],
  },
  {
    id: 'around-rock', name: 'いわを よけて', hint: 'いわは ほれない。よこを ほってみよう', need: 20,
    map: [
      '........................',
      '........................',
      '.......ssssssssss.......',
      '......ssggssssggss......',
      '.....sssggssssssggsss...',
      '.....ssssssssssssssss...',
      'dddddddddddddddddddddddd',
      'dddddddddddddddddddddddd',
      'ddddddddddrrrrdddddddddd',
      'dddddddddrrrrrrddddddddd',
      'ddddddddrrrrrrrrdddddddd',
      'dddddddddddddddddddddddd',
      'rrrddddddddddddddddddrrr',
      'rrrr................rrrr',
      'rrrr................rrrr',
      'rrrrr..............rrrrr',
      'rrrrr..............rrrrr',
      'rrrrrr............rrrrrr',
      'rrrrrr............rrrrrr',
      'rrrrrrr..........rrrrrrr',
      'rrrrrrr..........rrrrrrr',
      'rrrrrrrr........rrrrrrrr',
      'rrrrrrrr........rrrrrrrr',
      'rrrrrrrrr......rrrrrrrrr',
      'rrrrrrrrr......rrrrrrrrr',
      'rrrrrrrrr......rrrrrrrrr',
      'rrrrrrrrr......rrrrrrrrr',
      'rrrrrrrrr......rrrrrrrrr',
      'rrrrrrrrrbbbbbbrrrrrrrrr',
      'rrrrrrrrrbbbbbbrrrrrrrrr',
      'rrrrrrrrrbbbbbbrrrrrrrrr',
      'rrrrrrrrrrrrrrrrrrrrrrrr',
    ],
  },
  {
    id: 'wash-down', name: 'みずで ながそう', hint: 'つちの かべを ほろう。「みず」を かけても ながれるよ', need: 24,
    map: [
      '.......d................',
      'wwwwwwwd................',
      'wwwwwwwd................',
      'wwwwwwwd................',
      'wwwwwwwd................',
      'wwwwwwwd................',
      'wwwwwwwd................',
      'wwwwwwwd................',
      'wwwwwwwd................',
      'wwwwwwwd....gg..gg......',
      'wwwwwwwd..gggggggg......',
      'rrrrrrrrrrrrrrrrrrr.rrrr',
      'rrrrrrrrrrrrrrrrrrr.rrrr',
      'rrrrrrrrrrrrrrrrrrr.rrrr',
      'rrrrrrrrrrrrrrrrrrr.rrrr',
      'rrrrrrrrrrrrrrrrrrr.rrrr',
      'rrrrrrrrrrrrrrrrrrr.rrrr',
      'rrrrrrrrrrrrrrrrrrr.rrrr',
      'rrrrrrrrrrrrrrrrrrr.rrrr',
      'rrrrrrrrrrrrrrr.......rr',
      'rrrrrrrrrrrrrrr.......rr',
      'rrrrrrrrrrrrrrr.......rr',
      'rrrrrrrrrrrrrrr.......rr',
      'rrrrrrrrrrrrrrr.......rr',
      'rrrrrrrrrrrrrrr.......rr',
      'rrrrrrrrrrrrrrr.......rr',
      'rrrrrrrrrrrrrrr.......rr',
      'rrrrrrrrrrrrrrr.......rr',
      'rrrrrrrrrrrrrrrbbbbbbbrr',
      'rrrrrrrrrrrrrrrbbbbbbbrr',
      'rrrrrrrrrrrrrrrbbbbbbbrr',
      'rrrrrrrrrrrrrrrrrrrrrrrr',
    ],
  },
  {
    id: 'mind-the-hole', name: 'あなに きをつけて', hint: 'たからばこの まうえを ほろう', need: 14,
    map: [
      '........................',
      '........................',
      '.....ssssssssss.........',
      '....ssggssssggss........',
      '...ssssggssggssss.......',
      '..ssssssssssssssss......',
      'rrrrddddddddddddddddrrrr',
      'rrrrddddddddddddddddrrrr',
      'rrrrddddddddddddddddrrrr',
      'rrrr................rrrr',
      'rrrr................rrrr',
      'rrrr................rrrr',
      'rrrr................rrrr',
      'rrrr................rrrr',
      'rrrr................rrrr',
      'rrrr................rrrr',
      'rrrr................rrrr',
      'rrrr................rrrr',
      'rrrr................rrrr',
      'rrrr................rrrr',
      'rrrr................rrrr',
      'rrrr................rrrr',
      'rrrr................rrrr',
      'rrrr................rrrr',
      'rrrr................rrrr',
      'rrrr................rrrr',
      'rrrr................rrrr',
      'rrrroooorrbbbbrroooorrrr',
      'rrrroooorrbbbbrroooorrrr',
      'rrrrrrrrrrbbbbrrrrrrrrrr',
      'rrrrrrrrrrbbbbrrrrrrrrrr',
      'rrrrrrrrrrrrrrrrrrrrrrrr',
    ],
  },
  {
    id: 'build-a-slide', name: 'すべりだいを つくろう', hint: 'いしで すべりだいを かいて、たからばこへ', need: 16,
    map: [
      '........................',
      '........................',
      '..ssssss................',
      '.ssggggss...............',
      '.ssggggss...............',
      'ddddddddd...............',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      'ooooooooooor............',
      'ooooooooooorrrbbbbbbrrrr',
      'rrrrrrrrrrrrrrbbbbbbrrrr',
      'rrrrrrrrrrrrrrbbbbbbrrrr',
      'rrrrrrrrrrrrrrbbbbbbrrrr',
      'rrrrrrrrrrrrrrrrrrrrrrrr',
    ],
  },
  {
    id: 'spring-stream', name: 'いずみの ながれ', hint: 'つちの せんを ほると、みずが ながれだすよ', need: 30,
    map: [
      '........................',
      '........................',
      'ffff....................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '.......d.....gg..gg.....',
      '.......d...gggggggg.....',
      'rrrrrrrrrrrrrrrrrrrr....',
      'rrrrrrrrrrrrrrrrrrrr....',
      'rrrrrrrrrrrrrrrrrrrr....',
      'rrrrrrrrrrrrrrrrrrrr....',
      'rrrrrrrrrrrrrrrrrrrr....',
      'rrrrrrrrrrrrrrrrrrrr....',
      'rrrrrrrrrrrrrrrrrrrr....',
      'rrrrrrrrrrrrrrrrrrrr....',
      'rrrrrrrrrrrrrrrrrrrr....',
      'rrrrrrrrrrrrrrrrrrr.....',
      'rrrrrrrrrrrrrrrrrr......',
      'rrrrrrrrrrrrrrrrrr......',
      'rrrrrrrrrrrrrrrrrr......',
      'rrrrrrrrrrrrrrrrrrbbbbbb',
      'rrrrrrrrrrrrrrrrrrbbbbbb',
      'rrrrrrrrrrrrrrrrrrbbbbbb',
      'rrrrrrrrrrrrrrrrrrrrrrrr',
    ],
  },
  {
    id: 'two-ways', name: 'ふたつの みち', hint: 'たからばこに つながる みちは どっちかな', need: 16,
    map: [
      '........................',
      '........................',
      '........ssssss..........',
      '.......ssggggss.........',
      '......sssggggsss........',
      '.....ssssssssssss.......',
      'rrrrrddddddddddddrrrrrrr',
      'rrrrrd....rr....drrrrrrr',
      'rrrrrd...rrrr...drrrrrrr',
      'rrrrrd..rrrrrr..drrrrrrr',
      'rrrrrd.rrrrrrrr.drrrrrrr',
      'rrrrrdrrrrrrrrrrdrrrrrrr',
      'rrrrrdrrrrrrrrrrdrrrrrrr',
      'rrrrr.rrrrrrrrrr.rrrrrrr',
      'rrrrr.rrrrrrrrrr.rrrrrrr',
      'rrrrr.rrrrrrrrrr.rrrrrrr',
      'rrrrr.rrrrrrrrrr.rrrrrrr',
      'rrrrr.rrrrrrrrrr.rrrrrrr',
      'rrrrr.rrrrrrrrrr.rrrrrrr',
      'rrrrr.rrrrrrrrrr.rrrrrrr',
      'rrrrr.rrrrrrrrrr.rrrrrrr',
      'rrrrrorrrrrrrrrr.rrrrrrr',
      'rrrrrorrrrrrrrrr.rrrrrrr',
      'rrrrrrrrrrrrrrrr.rrrrrrr',
      'rrrrrrrrrrrrrrrr.rrrrrrr',
      'rrrrrrrrrrrrrrr...rrrrrr',
      'rrrrrrrrrrrrrr.....rrrrr',
      'rrrrrrrrrrrrrr.....rrrrr',
      'rrrrrrrrrrrrrrbbbbbrrrrr',
      'rrrrrrrrrrrrrrbbbbbrrrrr',
      'rrrrrrrrrrrrrrbbbbbrrrrr',
      'rrrrrrrrrrrrrrrrrrrrrrrr',
    ],
  },
  {
    id: 'under-water', name: 'みずの そこの たから', hint: 'みずの なかでは たからが さきに しずむよ', need: 20,
    map: [
      '........................',
      '........................',
      'rrr..................rrr',
      'rrrwwwwwwwwwwwwwwwwwwrrr',
      'rrrwwwwwwwwwwwwwwwwwwrrr',
      'rrrwwwwwwwwwwwwwwwwwwrrr',
      'rrrwwwwwwwwwwwwwwwwwwrrr',
      'rrrwwwwwwwwwwwwwwwwwwrrr',
      'rrrwwssggsswwssggsswwrrr',
      'rrrsssggggssssggggsssrrr',
      'rrrssssssssssssssssssrrr',
      'rrrddddddddddddddddddrrr',
      'rrrddddddddddddddddddrrr',
      'rrr..................rrr',
      'rrr..................rrr',
      'rrr..................rrr',
      'rrr..................rrr',
      'rrr..................rrr',
      'rrr..................rrr',
      'rrr..................rrr',
      'rrr..................rrr',
      'rrr..................rrr',
      'rrr..................rrr',
      'rrr..................rrr',
      'rrr..................rrr',
      'rrr..................rrr',
      'rrrooorrrrbbbbrrrrooorrr',
      'rrrooorrrrbbbbrrrrooorrr',
      'rrrrrrrrrrbbbbrrrrrrrrrr',
      'rrrrrrrrrrbbbbrrrrrrrrrr',
      'rrrrrrrrrrbbbbrrrrrrrrrr',
      'rrrrrrrrrrrrrrrrrrrrrrrr',
    ],
  },
  {
    id: 'cave-maze', name: 'ちかの めいろ', hint: 'いわの すきまを つないで、ながい トンネルを ほろう', need: 14,
    map: [
      '........................',
      '........................',
      '....ssssssssss..........',
      '...ssggssssggss.........',
      '..sssggssssssggsss......',
      '..ssssssssssssssss......',
      'dddddddddddddddddddddddd',
      'dddddddddddddddddddddddd',
      'dddddddddddddddddddddddd',
      'dddddddddddddddddddddddd',
      'rrrrrrrrrrrdddddrrrrrrrr',
      'rrrrrrrrrrrdddddrrrrrrrr',
      'dddddddddddddddddddddddd',
      'dddddddddddddddddddddddd',
      'dddddddddddddddddddddddd',
      'dddddddddddddddddddddddd',
      'dddddddddddddddddddddddd',
      'rrrrrrrdddddrrrrrrrrrrrr',
      'rrrrrrrdddddrrrrrrrrrrrr',
      'dddddddddddddddddddddddd',
      'dddddddddddddddddddddddd',
      'dddddddddddddddddddddddd',
      'dddddddddddddddddddddddd',
      'dddddddddddddddddddddddd',
      'rrrrrrrrrrdddddrrrrrrrrr',
      'rrrrrrrrrrdddddrrrrrrrrr',
      'dddddddddddddddddddddddd',
      'rrrrrrrrrbbbbbbrrrrrrrrr',
      'rrrrrrrrrbbbbbbrrrrrrrrr',
      'rrrrrrrrrbbbbbbrrrrrrrrr',
      'rrrrrrrrrbbbbbbrrrrrrrrr',
      'rrrrrrrrrrrrrrrrrrrrrrrr',
    ],
  },
  {
    id: 'treasure-mountain', name: 'たからの やま', hint: 'みずも つかって、やまの たからを ぜんぶ あつめよう', need: 30,
    map: [
      '.........ffff...........',
      '........................',
      '.......ssssssss.........',
      '.....ssssggssssss.......',
      '....ssggssssssggss......',
      '...sssssssggssssssss....',
      '..ssssggsssssssssggss...',
      '..sssssssssssssssssss...',
      'dddddddddddddddddddddddd',
      'dddddddddddddddddddddddd',
      'dddddddddddddddddddddddd',
      'rrrrdddddddddddddddddrrr',
      'rrrrrdddddddddddddddrrrr',
      'rrrrrrdddddddddddddrrrrr',
      'rrrrrrr...........rrrrrr',
      'rrrrrrr...........rrrrrr',
      'rrrrrrrr.........rrrrrrr',
      'rrrrrrrr.........rrrrrrr',
      'rrrrrrrrr.......rrrrrrrr',
      'rrrrrrrrr.......rrrrrrrr',
      'rrrrrrrrr.......rrrrrrrr',
      'rrrrrrrrr.......rrrrrrrr',
      'rrrrrrrrr.......rrrrrrrr',
      'rrrrrrrrr.......rrrrrrrr',
      'rrrrrrrrr.......rrrrrrrr',
      'rrrrrrrrro.....orrrrrrrr',
      'rrrrrrrrro.....orrrrrrrr',
      'rrrrrrrrrrbbbbbrrrrrrrrr',
      'rrrrrrrrrrbbbbbrrrrrrrrr',
      'rrrrrrrrrrbbbbbrrrrrrrrr',
      'rrrrrrrrrrbbbbbrrrrrrrrr',
      'rrrrrrrrrrrrrrrrrrrrrrrr',
    ],
  },
]
