import { expect, test } from '@playwright/test'
import { capturePageErrors } from './support/runtimeErrors'

test('builds, rolls, celebrates, undoes and re-enters the marble workshop', async ({ page }, testInfo) => {
  const errors = capturePageErrors(page)
  await page.goto('/')
  await page.getByRole('link', { name: '3Dビーだまコースづくり', exact: true }).click()
  const roll = page.getByRole('button', { name: 'ビーだま ころがす！', exact: true })
  await expect(roll).toBeEnabled({ timeout: 20_000 })
  await page.getByRole('button', { name: 'まっすぐを ついか', exact: true }).click()
  await page.getByRole('button', { name: 'ゴールを ついか', exact: true }).click()
  await expect(page.getByText('3 / 36', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('course-portrait.png') })
  await roll.click()
  await expect(page.getByText('⭐ ゴール！ やったね！', { exact: true })).toBeVisible({ timeout: 15_000 })
  await page.screenshot({ path: testInfo.outputPath('goal-portrait.png') })
  await page.getByRole('button', { name: 'クリア', exact: true }).click()
  await expect(roll).toBeDisabled()
  await page.getByRole('button', { name: 'もどす', exact: true }).click()
  await expect(page.getByText('3 / 36', { exact: true })).toBeVisible()
  await page.setViewportSize({ width: 844, height: 390 })
  await expect(roll).toBeInViewport()
  await page.screenshot({ path: testInfo.outputPath('course-landscape.png') })
  await page.getByRole('button', { name: 'もどる', exact: true }).click()
  await expect(page.locator('canvas')).toHaveCount(0)
  await page.getByRole('link', { name: '3Dビーだまコースづくり', exact: true }).click()
  await expect(roll).toBeEnabled({ timeout: 20_000 })
  await expect(page.locator('canvas')).toHaveCount(1)
  expect(errors).toEqual([])
})

test('touch-drag adds a part, cancellation rolls back, and rotation/keyboard placement remain available', async ({ page }, testInfo) => {
  await page.goto('/games/marble-course')
  const palette = page.getByRole('button', { name: 'カーブを ついか', exact: true })
  await expect(palette).toBeEnabled({ timeout: 20_000 })
  const source = (await palette.boundingBox())!
  const scene = (await page.getByTestId('marble-scene').boundingBox())!
  const client = await page.context().newCDPSession(page)
  await client.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: source.x + source.width / 2, y: source.y + source.height / 2 }] })
  await client.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: scene.x + scene.width * 0.65, y: scene.y + scene.height * 0.55 }] })
  await client.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(page.getByText('2 / 36', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'まわす', exact: true }).click()
  await page.getByTestId('marble-scene').press('ArrowRight')
  await page.getByTestId('marble-scene').press('Enter')
  await client.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: source.x + source.width / 2, y: source.y + source.height / 2 }] })
  await client.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: scene.x + scene.width * 0.25, y: scene.y + scene.height * 0.5 }] })
  await client.send('Input.dispatchTouchEvent', { type: 'touchCancel', touchPoints: [] })
  await expect(page.getByText('2 / 36', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'ぶんきを ついか', exact: true }).click()
  await page.getByRole('button', { name: 'ゴールを ついか', exact: true }).click()
  await page.screenshot({ path: testInfo.outputPath('parts-portrait.png') })
})
