import { expect, test } from '@playwright/test'
import { capturePageErrors } from './support/runtimeErrors'

test('3Dレースを操作して退出し、新しいengineで再入場できる [circuit-racing]', async ({ page }) => {
  const errors = capturePageErrors(page)
  await page.goto('/')
  await page.getByRole('link', { name: 'サーキットレース', exact: true }).click()
  const begin = page.getByRole('button', { name: 'レースを はじめる', exact: true })
  // モデル・WebGL初期化を示す実際のready状態を待つ。経過秒や順位には依存しない。
  await expect(begin).toBeEnabled({ timeout: 15_000 })
  await begin.click()
  await page.getByRole('button', { name: 'みちばた', exact: true }).click()
  await expect(page.getByRole('button', { name: 'みちばた', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('canvas')).toHaveCount(1)
  await page.getByRole('button', { name: /えらびなおす/ }).click()
  await page.locator('[data-game-back-button]').click()
  await expect(page.getByRole('heading', { name: 'こどもミニゲーム', exact: true })).toBeVisible()
  await expect(page.locator('canvas')).toHaveCount(0)
  await page.getByRole('link', { name: 'サーキットレース', exact: true }).click()
  await expect(begin).toBeEnabled({ timeout: 15_000 })
  await begin.click()
  await expect(page.getByRole('region', { name: 'レースの そうさ', exact: true })).toBeVisible()
  await expect(page.locator('canvas')).toHaveCount(1)
  expect(errors).toEqual([])
})

test('クレーンゲームでアームを動かしてつかみ、退出して再入場できる [crane-game]', async ({ page }) => {
  test.setTimeout(90_000)
  const errors = capturePageErrors(page)
  await page.goto('/')
  await page.getByRole('link', { name: 'クレーンゲーム', exact: true }).click()
  const begin = page.getByRole('button', { name: 'あそぶ！', exact: true })
  // WebGLとRapierの初期化を示す実際のready状態を待つ。景品が取れたかどうかには依存しない。
  await expect(begin).toBeEnabled({ timeout: 20_000 })
  await page.getByRole('button', { name: 'カプセルの きかいを えらぶ', exact: true }).click()
  await begin.click()
  const scene = page.getByTestId('crane-scene')
  await expect.poll(() => scene.getAttribute('data-ready'), { timeout: 20_000 }).toBe('true')
  const parked = await scene.getAttribute('data-claw-x')
  await page.getByRole('button', { name: 'よこに うごかす', exact: true }).click()
  await expect.poll(() => scene.getAttribute('data-claw-x')).not.toBe(parked)
  await page.getByRole('button', { name: 'よこに うごくのを とめる', exact: true }).click()
  await page.getByRole('button', { name: 'つかむ', exact: true }).click()
  await expect.poll(() => scene.getAttribute('data-phase')).not.toBe('idle')
  // 降ろす・つかむ・運ぶ・放すまで一巡し、穴の上へ戻ってくる。
  await expect.poll(() => scene.getAttribute('data-phase'), { timeout: 30_000 }).toBe('idle')
  expect(Number(await scene.getAttribute('data-claw-x'))).toBeCloseTo(-0.46, 2)
  await page.getByRole('button', { name: 'よこから みる', exact: true }).click()
  await expect(scene).toHaveAttribute('data-view', 'side')
  await expect(page.locator('canvas')).toHaveCount(1)
  expect(Number(await scene.getAttribute('data-draw-calls'))).toBeLessThan(90)
  expect(Number(await scene.getAttribute('data-triangles'))).toBeLessThan(120_000)
  await page.locator('[data-game-back-button]').click()
  await expect(begin).toBeVisible()
  await page.locator('[data-game-back-button]').click()
  await expect(page.getByRole('heading', { name: 'こどもミニゲーム', exact: true })).toBeVisible()
  await expect(page.locator('canvas')).toHaveCount(0)
  await page.getByRole('link', { name: 'クレーンゲーム', exact: true }).click()
  await expect(begin).toBeEnabled({ timeout: 20_000 })
  await begin.click()
  await expect(page.getByRole('region', { name: 'クレーンの そうさ', exact: true })).toBeVisible()
  await expect(page.locator('canvas')).toHaveCount(1)
  expect(errors).toEqual([])
})
